---
- name: Run command on routers
  hosts: routers
  gather_facts: no
  pre_tasks:
    - name: Install required collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r /runner/project/router_cmd/requirements.yml
      delegate_to: localhost
      run_once: true
  tasks:
    - name: Execute command
      ansible.netcommon.cli_command:
        command: "{{ cmd }}"
